[project]
name = "karatekids-gcloud-functions"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "functions-framework>=3.10.1",
    "google-cloud-storage>=3.10.1",
    "requests>=2.33.1",
]

[tool.uv]
exclude-newer = "2026-04-27T00:00:00Z"
package = false
